services:
  ai-agent:
    build: .
    container_name: ai-agent-nas
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - TZ=${GENERIC_TIMEZONE:-Asia/Singapore}
      # postgre db init configuration
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
      - POSTGRES_USER=${POSTGRES_USER:-n8nuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # db for n8n workflow init configuration
      - N8N_POSTGRES_DB=${N8N_POSTGRES_DB:-ai_agent}
      - N8N_POSTGRES_USER=${N8N_POSTGRES_USER:-aiagentuser}
      - N8N_POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost:5678}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://${N8N_HOST}:5678}
      - VECTOR_SIZE=${VECTOR_SIZE:-3072}
      - PORT=${N8N_SERVER_PORT:-5000}
      - FLASK_DEBUG=false
      # db for n8n admin configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=localhost
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8nuser}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/data
      - ./postgresql-data:/var/lib/postgresql
      - ./n8n-data:/root/.n8n
      - ./n8n-service/service_account.json:/app/n8n-service/service_account.json:ro
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432" # PostgreSQL
      - "${N8N_PORT:-5678}:5678" # n8n
      - "${N8N_SERVER_PORT:-5000}:5000" # n8n-server
    restart: unless-stopped
